# Generated by Django 5.2.13 on 2026-04-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePickupStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('stop_order', models.PositiveIntegerField(default=1)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_stops', to='rides.ride')),
            ],
            options={
                'ordering': ['stop_order', 'id'],
                'unique_together': {('ride', 'stop_order')},
            },
        ),
    ]
